version: 2
updates:
  # .NET package dependencies across the repository
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  # All Node.js dependencies across the repository
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Docker image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
