// <auto-generated />
using System;
using Backlog.Tracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backlog.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20260611162728_AddCloudWatchTable")]
    partial class AddCloudWatchTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("Backlog.Tracking.CloudwatchSummaryLogLine", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LambdaReport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastInfoMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastWarningMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkLogicUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NcnReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TreReference")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.HasIndex("NcnReference");

                    b.HasIndex("TreReference");

                    b.ToTable("CloudwatchSummaryLogLines");
                });

            modelBuilder.Entity("Backlog.Tracking.TrackerLine", b =>
                {
                    b.Property<Guid>("SourceUuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParserRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Court")
                        .HasColumnType("TEXT");

                    b.Property<string>("CsvMetadataHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ncn")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TrackerLineLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackerStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TreReference")
                        .HasColumnType("TEXT");

                    b.HasKey("SourceUuid", "ParserRunId");

                    b.ToTable("ParserEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
