// <auto-generated />
using System;
using Backlog.Tracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backlog.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("Backlog.Tracking.TrackerLine", b =>
                {
                    b.Property<Guid>("SourceUuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParserRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Court")
                        .HasColumnType("TEXT");

                    b.Property<string>("CsvMetadataHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ncn")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TrackerLineLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackerStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TreReference")
                        .HasColumnType("TEXT");

                    b.HasKey("SourceUuid", "ParserRunId");

                    b.ToTable("ParserEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
